#!/bin/bash
# Create repo root .env for Docker prod from apps/backend/.env (run on server once).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

BACKEND_ENV="$REPO_ROOT/apps/backend/.env"
ROOT_ENV="$REPO_ROOT/.env"

if [[ ! -f "$BACKEND_ENV" ]]; then
  echo "ERROR: $BACKEND_ENV not found. Copy .env.example and edit MySQL credentials first."
  exit 1
fi

# shellcheck disable=SC1090
source "$BACKEND_ENV"

docker_url="${DATABASE_URL_DOCKER:-}"
docker_sync="${DATABASE_URL_SYNC_DOCKER:-}"

if [[ -z "$docker_url" && -n "${DATABASE_URL:-}" ]]; then
  docker_url="${DATABASE_URL/@localhost:/@host.docker.internal:}"
  docker_sync="${DATABASE_URL_SYNC/@localhost:/@host.docker.internal:}"
fi

if [[ -z "$docker_url" ]]; then
  echo "ERROR: Set DATABASE_URL in apps/backend/.env or DATABASE_URL_DOCKER in .env"
  exit 1
fi

if [[ -f "$ROOT_ENV" ]]; then
  echo "Root .env already exists at $ROOT_ENV"
  echo "Ensure it contains:"
  echo "  DATABASE_URL_DOCKER=$docker_url"
  echo "  DATABASE_URL_SYNC_DOCKER=$docker_sync"
  exit 0
fi

cp .env.example "$ROOT_ENV"

# Append / override docker DB lines (password already URL-encoded in backend .env)
cat >>"$ROOT_ENV" <<EOF

# --- generated by server-setup-env.sh ---
DATABASE_URL=$DATABASE_URL
DATABASE_URL_SYNC=$DATABASE_URL_SYNC
DATABASE_URL_DOCKER=$docker_url
DATABASE_URL_SYNC_DOCKER=$docker_sync
REDIS_URL=redis://redis:6379/0
RECOGNITION_SERVICE_URL=http://recognition:6003
NEXT_PUBLIC_API_URL=https://attendance.akshanshconsultancy.com
CORS_ORIGINS=https://attendance.akshanshconsultancy.com
EOF

echo "Created $ROOT_ENV"
echo "Edit JWT_SECRET, JWT_REFRESH_SECRET, EMBEDDING_ENCRYPTION_KEY before prod use."
echo "Then: docker compose --profile prod up -d --force-recreate"
echo "      docker compose exec backend alembic upgrade head"
echo "      docker compose exec backend python -m app.seed"
